# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='home_page_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
