# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 00:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_home_page_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='project/')),
                ('video', models.CharField(blank=True, max_length=100)),
                ('copy', models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='featured_image',
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='image',
            field=models.ImageField(blank=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='home_page_image',
            field=models.ImageField(upload_to='project/'),
        ),
        migrations.AddField(
            model_name='projectmedia',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Project'),
        ),
    ]
