# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-24 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_auto_20180324_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmedia',
            name='video',
            field=models.CharField(blank=True, help_text='Vimeo ID.<br>Example: ID is 123 if url is https://www.vimeo.com/123', max_length=100),
        ),
    ]
